### ISSUE TITLE
[CRASH] 12.0.3 version problem

### ISSUE THREAD

**Issue by oskarbukovsky** [Darkhax-Minecraft/Max-Health-Fix#12]
### Minecraft Version

1.20.1

### Mod Version

12.0.3

### Mod Loader

Forge

### What environment are you running the mod in?

Dedicated Server

### Issue Description

When running 12.0.2 version of mod everything works fine, but we have problems with curios items which add extra health, when players tp between dims their actual health is reset to 1-20. Maximum stays, but healing every time you have to teleport home/explore is really annoying.

Things broke only when updating to 12.0.3 of max-health-fix

### Crash Log

[crash-2024-08-06_14.15.45-fml.txt](https://github.com/user-attachments/files/16510138/crash-2024-08-06_14.15.45-fml.txt)

**Comment by Darkhax** [comment]
Hello, it looks like something else on your server is preventing the PlayerList from loading which is crashing MaxHealthFix and several other mods that you have installed. This generally happens when a mod is injecting unsafe code. I would recommend checking your latest.log file for any errors related to the PlayerList before the crash occurs.
